define({
  "date": "تاريخ:",
  "greeting": "صباح الخير",
	"username" : "اسم المستخدم",
	"password" :"كلمة المرور",
	"login" : "الدخول",
	"reset" : "إعادة تعيين",
	"ok":"موافق",
	"wrongUserNameAndPassword" : "يوجد خطأ في اسم المستخدم و كلمة المرور",
	"errorDialogTitle" : "خطأ بالدخول",
	"loginPage" : "شاشة الدخول",
	"phonebook": "سجل الهاتف",
	"empUserName":"الرقم الوظيفي" ,
		"empFullName" :"الإسم الكامل",
		"empNumber":"رقم الموظف",
		
		"empEmailAddress":"البريد الإلكتروني",
		"empGradeName" :"الرتبة",
		"empPositionName" :"المنصب",
		"empOrgName" : "المنظمة",
		"empSupervisor" : "المدير المباشر",
		"back": "الرجوع",
		"emptyUserNameAndPassword" : "الرجاء ادخال اسم المستخدم و كلمة المرور",
		"mobileAppName" : "EBS Mobile Application",
		"profile" : "الملف الشخصي",
		"worklist": "الاشعارات",
		"about" : "حول",
		"requests": "طلبات",
		"addRequest": "إضافة طلب",
		"requestDate": "تاريخ الطلب",
		"employmentCertificationName": "اسم الشهادة",
		"toWhomArabic" : "إلى من بالعربي",
		"endosermentRequired" : "موافقة مطلوبة",
		"justification" : "مبرر",
		"noOfCopies" : "عدد النسخ",
		"status": "الحالة",
		"submit" : "إرسال",
		"saveAndSubmit" : "حفظ و إرسال",
		"requestHistoryList": "سجل الطلبات",
		"addRequest" : "إضافة طلب",
		"requestApproversList" : "قائمة الموافقون",
		"request": "الطلب",
		"yes":"نعم",
		"no":"لا"
});